# Generated by Django 2.1.5 on 2019-02-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190213_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=1028, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=1028, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=1028, null=True),
        ),
    ]
