# Generated by Django 2.1.5 on 2019-02-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20190217_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='content',
        ),
        migrations.AddField(
            model_name='lecture',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecture_type',
            field=models.CharField(choices=[('HTML', 'HTML'), ('VID', 'Video'), ('PIC', 'Picture')], default='HTML', max_length=5),
        ),
        migrations.AddField(
            model_name='lecture',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
