# Generated by Django 2.1.5 on 2019-02-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20190218_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='video',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
