# Generated by Django 2.1.5 on 2019-02-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20190220_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='order',
            field=models.IntegerField(),
        ),
    ]
