# Generated by Django 2.1.5 on 2019-02-24 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0009_auto_20190221_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='course',
            new_name='current_course',
        ),
        migrations.AddField(
            model_name='progress',
            name='completed_courses',
            field=models.ManyToManyField(related_name='progress_courses', to='course.Course'),
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('current_course', 'owner')},
        ),
    ]
