# Generated by Django 2.1.5 on 2019-02-24 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20190224_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.Unit'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='completed_courses',
            field=models.ManyToManyField(related_name='progress_lessons', to='course.Lesson'),
        ),
    ]
