# Generated by Django 2.1.5 on 2019-02-24 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0013_auto_20190224_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='current_course',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons_course', to='course.Course'),
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('course', 'owner')},
        ),
    ]
