# Generated by Django 2.1.5 on 2019-02-25 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20190224_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='course.Unit'),
            preserve_default=False,
        ),
    ]
