# Generated by Django 2.1.5 on 2019-02-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20190225_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='value',
            new_name='total_lessons',
        ),
    ]
