# Generated by Django 2.1.5 on 2019-04-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_auto_20190314_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='completed_units',
            field=models.ManyToManyField(related_name='progress_units', to='course.Unit'),
        ),
    ]
