# Generated by Django 2.1.5 on 2019-03-01 21:46

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190301_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='headshot',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='headshots/', verbose_name='Headshot'),
        ),
        migrations.AddField(
            model_name='user',
            name='headshot_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
    ]
