# Generated by Django 2.1.5 on 2019-03-01 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190301_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='headshot_ppoi',
        ),
    ]
