# Generated by Django 2.1.5 on 2019-03-01 22:23

import atktut.users.models
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_headshot_ppoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headshot',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=atktut.users.models.userPicture, verbose_name='Headshot'),
        ),
    ]
