# Generated by Django 2.1.5 on 2019-03-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_question_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.CharField(blank=True, max_length=1028, null=True),
        ),
    ]
